package model

type Report struct {
	Aiid                    string `json:"aiid"`
	AllExp                  string `json:"all_exp"`
	AllSkillInfo            string `json:"all_skill_info"`
	Ambush                  int    `json:"ambush"`
	AttackAdvance           string `json:"attack_advance"`
	AttackAllHeroInfo       string `json:"attack_all_hero_info"`
	AttackAllSurface        string `json:"attack_all_surface"`
	AttackArmyGroup         string `json:"attack_army_group"`
	AttackBaseHeroid        int    `json:"attack_base_heroid"`
	AttackBaseLevel         int    `json:"attack_base_level"`
	AttackClanName          string `json:"attack_clan_name"`
	AttackClanid            int    `json:"attack_clanid"`
	AttackFightEventCount   int    `json:"attack_fight_event_count"`
	AttackFightEventFacade  int    `json:"attack_fight_event_facade"`
	AttackHelpID            string `json:"attack_help_id"`
	AttackHeroPolicy        string `json:"attack_hero_policy"`
	AttackHeroType          string `json:"attack_hero_type"`
	AttackHeroTypeAdvance   string `json:"attack_hero_type_advance"`
	AttackHp                int    `json:"attack_hp"`
	AttackIdu               string `json:"attack_idu"`
	AttackName              string `json:"attack_name"`
	AttackRoleID            string `json:"attack_role_id"`
	AttackShipType          int    `json:"attack_ship_type"`
	AttackUnionName         string `json:"attack_union_name"`
	AttackUnionOfficial     int    `json:"attack_union_official"`
	AttackUnionid           int    `json:"attack_unionid"`
	AttackerArmyEffect      string `json:"attacker_army_effect"`
	AttackerBaseHeroDetail  string `json:"attacker_base_hero_detail"`
	AttackerForce           int    `json:"attacker_force"`
	AttackerGearInfo        string `json:"attacker_gear_info"`
	AttackerGongxun         int    `json:"attacker_gongxun"`
	AttackerLifeEndTime     string `json:"attacker_life_end_time"`
	AttackerMachineStatInfo string `json:"attacker_machine_stat_info"`
	AttackerSurface         string `json:"attacker_surface"`
	AttackerXwc             int    `json:"attacker_xwc"`
	Bandit                  int    `json:"bandit"`
	BattleID                int    `json:"battle_id" gorm:"primary_key"`
	BattleScenes            int    `json:"battle_scenes"`
	BlockID                 int    `json:"block_id"`
	BorrowLand              int    `json:"borrow_land"`
	CityType                int    `json:"city_type"`
	DefendAdvance           string `json:"defend_advance"`
	DefendAllHeroInfo       string `json:"defend_all_hero_info"`
	DefendAllSurface        string `json:"defend_all_surface"`
	DefendArmyGroup         string `json:"defend_army_group"`
	DefendBaseHeroid        int    `json:"defend_base_heroid"`
	DefendBaseLevel         int    `json:"defend_base_level"`
	DefendClanName          string `json:"defend_clan_name"`
	DefendClanid            int    `json:"defend_clanid"`
	DefendFightEventCount   int    `json:"defend_fight_event_count"`
	DefendFightEventFacade  int    `json:"defend_fight_event_facade"`
	DefendHelpID            string `json:"defend_help_id"`
	DefendHeroPolicy        string `json:"defend_hero_policy"`
	DefendHeroType          string `json:"defend_hero_type"`
	DefendHeroTypeAdvance   string `json:"defend_hero_type_advance"`
	DefendHp                int    `json:"defend_hp"`
	DefendIdu               string `json:"defend_idu"`
	DefendName              string `json:"defend_name"`
	DefendRoleID            string `json:"defend_role_id"`
	DefendShipType          int    `json:"defend_ship_type"`
	DefendUnionName         string `json:"defend_union_name"`
	DefendUnionOfficial     int    `json:"defend_union_official"`
	DefendUnionid           int    `json:"defend_unionid"`
	DefenderArmyEffect      string `json:"defender_army_effect"`
	DefenderBaseHeroDetail  string `json:"defender_base_hero_detail"`
	DefenderForce           int    `json:"defender_force"`
	DefenderGearInfo        string `json:"defender_gear_info"`
	DefenderGongxun         int    `json:"defender_gongxun"`
	DefenderLifeEndTime     string `json:"defender_life_end_time"`
	DefenderMachineStatInfo string `json:"defender_machine_stat_info"`
	DefenderSurface         string `json:"defender_surface"`
	DefenderXwc             int    `json:"defender_xwc"`
	ExtraResult             int    `json:"extra_result"`
	FightType               int    `json:"fight_type"`
	FirstOccupyLvnLand      int    `json:"first_occupy_lvn_land"`
	Garrison                int    `json:"garrison"`
	HuangjinConvert         int    `json:"huangjin_convert"`
	InNightMode             int    `json:"in_night_mode"`
	IsAi                    int    `json:"is_ai"`
	IsShared                int    `json:"is_shared"`
	LoseTips                string `json:"lose_tips"`
	MachineEffect           string `json:"machine_effect"`
	Military                int    `json:"military"`
	MilitaryEffect          int    `json:"military_effect"`
	MvpSvpPos               string `json:"mvp_svp_pos"`
	NationMemberUnionInfo   string `json:"nation_member_union_info"`
	NoOwnerRes              int    `json:"no_owner_res"`
	Npc                     int    `json:"npc"`
	PressAttack             int    `json:"press_attack"`
	ReferenceCount          int    `json:"reference_count"`
	ResType                 int    `json:"res_type"`
	Result                  int    `json:"result"`
	Rob                     int    `json:"rob"`
	SandExtraInfo           string `json:"sand_extra_info"`
	ShipEffect              int    `json:"ship_effect"`
	TechJianJunEffect       int    `json:"tech_jian_jun_effect"`
	TechQuanXiangEffect     int    `json:"tech_quan_xiang_effect"`
	Time                    int    `json:"time"`
	Weather                 int    `json:"weather"`
	Wid                     int    `json:"wid"`
	WidName                 string `json:"wid_name"`
	WorldNpcArmy            string `json:"world_npc_army"`
	YiLingPressAttack       int    `json:"yi_ling_press_attack"`
}

func ToReport(data []any) {

}
